TRAIN_FILTER:
  - data/data_sensel_train/*/*

TRAIN_WEAK_FILTER:
  - data/data_weak_train/*/*

VAL_FILTER:
  - data/data_sensel_val/*/*

VAL_WEAK_FILTER:
  - data/data_weak_val/*/*

TEST_FILTER:
  - data/data_sensel_test/*/*

TEST_WEAK_FILTER:
  - data/data_weak_test/*/*

DO_AUG: True
AUG_METHOD: 1
WEAK_LABEL_HIGH_LOW: True
SKIP_FRAMES_WITHOUT_POSE: True
USE_SOFT_CROSS_ENTROPY: True
SOFT_CROSS_ENTROPY_OMEGA: 1
FORCE_CLASSIFICATION_NONZERO_WEIGHT: 1

LAMBDA_DOMAIN: 0.001
LAMBDA_FINGERS_SOURCE: 0.01
LAMBDA_FINGERS_TARGET: 0.01

NETWORK_TYPE: fpn_dann_logits
NETWORK_IMAGE_SIZE_X: 448
NETWORK_IMAGE_SIZE_Y:  448

MAX_EPOCHS: 30

LEARNING_RATE_INITIAL: 0.001
LEARNING_RATE_SCHEDULER_STEP:
  - 10
LEARNING_RATE_SCHEDULER_GAMMA: 0.1
BATCH_SIZE: 14

NUM_FORCE_CLASSES: 9
FORCE_THRESHOLDS:
  - 0.0
  - 0.5
  - 1.0
  - 2.0
  - 4.0
  - 8.0
  - 16.0
  - 32.0
  - 64.0

NETWORK_INPUT_CHANNELS: 3
DATALOADER_TRAIN_SKIP_FRAMES: 1   # Set to 1 to train on every frame, set to 5 to take every 5th frame
DATALOADER_TEST_SKIP_FRAMES: 10

NUM_WORKERS: 16

HAND_CROP: True
HAND_CROP_SCALE: 1.5

TRAIN_ITERS_PER_EPOCH: 10000

EXCLUDE_ACTIONS:
  - calibration
