# Thumb, index, middle, ring, pinky, palm (unused), force level
calibration:                      [-1, -1, -1, -1, -1, -1]
index_low:                        [0, 1, 0, 0, 0, 0]
index_high:                       [0, 1, 0, 0, 0, 0]
fingers_low:                      [1, 1, 1, 1, 1, 0]
fingers_high:                     [1, 1, 1, 1, 1, 0]
grasp_all-fingers_thumb-up_low:   [1, 1, 1, 1, 1, 0]
grasp_all-fingers_thumb-up_high:  [1, 1, 1, 1, 1, 0]
grasp_all-fingers_thumb-down_low: [1, 1, 1, 1, 1, 0]
grasp_all-fingers_thumb-down_high: [1, 1, 1, 1, 1, 0]
grasp_index_thumb-down_low:       [1, 1, 0, 0, 0, 0]
grasp_index_thumb-down_high:      [1, 1, 0, 0, 0, 0]
index_no-contact:                 [0, 0, 0, 0, 0, 0]
all-fingers_no-contact:           [0, 0, 0, 0, 0, 0]
grasp_all-fingers_no-contact:     [0, 0, 0, 0, 0, 0]
grasp_index_no-contact:           [0, 0, 0, 0, 0, 0]
index_low_uncurled:               [0, 1, 0, 0, 0, 0]
index_high_uncurled:              [0, 1, 0, 0, 0, 0]
index_slide_uncurled:             [0, 1, 0, 0, 0, 0]
index_no-contact_uncurled:        [0, 0, 0, 0, 0, 0]
index_low_curled:                 [0, 1, 0, 0, 0, 0]
index_high_curled:                [0, 1, 0, 0, 0, 0]
index_slide_curled:               [0, 1, 0, 0, 0, 0]
index_no-contact_curled:          [0, 0, 0, 0, 0, 0]
thumb_low:                        [1, 0, 0, 0, 0, 0]
thumb_high:                       [1, 0, 0, 0, 0, 0]
thumb_slide:                      [1, 0, 0, 0, 0, 0]
thumb_no-contact:                 [0, 0, 0, 0, 0, 0]
index-and-thumb_low:              [1, 1, 0, 0, 0, 0]
index-and-thumb_high:             [1, 1, 0, 0, 0, 0]
index-and-thumb_slide:            [1, 1, 0, 0, 0, 0]
index-and-thumb_no-contact:       [0, 0, 0, 0, 0, 0]
index-and-middle_low:             [0, 1, 1, 0, 0, 0]
index-and-middle_high:            [0, 1, 1, 0, 0, 0]
index-and-middle_slide:           [0, 1, 1, 0, 0, 0]
index-and-middle_no-contact:      [0, 0, 0, 0, 0, 0]
middle_low_uncurled:              [0, 0, 1, 0, 0, 0]
middle_high_uncurled:             [0, 0, 1, 0, 0, 0]
middle_slide_uncurled:            [0, 0, 1, 0, 0, 0]
middle_no-contact_uncurled:       [0, 0, 0, 0, 0, 0]
ring_low_uncurled:                [0, 0, 0, 1, 0, 0]
ring_high_uncurled:               [0, 0, 0, 1, 0, 0]
ring_slide_uncurled:              [0, 0, 0, 1, 0, 0]
ring_no-contact_uncurled:         [0, 0, 0, 0, 0, 0]
pinky_low:                        [0, 0, 0, 0, 1, 0]
pinky_high:                       [0, 0, 0, 0, 1, 0]
pinky_slide:                      [0, 0, 0, 0, 1, 0]
pinky_no-contact:                 [0, 0, 0, 0, 0, 0]
fingers_low_uncurled:             [1, 1, 1, 1, 1, 0]
fingers_high_uncurled:            [1, 1, 1, 1, 1, 0]
fingers_slide_uncurled:           [1, 1, 1, 1, 1, 0]
fingers_no-contact_uncurled:      [0, 0, 0, 0, 0, 0]
fingers-onebyone_low_uncurled:    [1, 1, 1, 1, 1, 0]
fingers-onebyone_high_uncurled:   [1, 1, 1, 1, 1, 0]
